from scrapers.functions.transcriber_data_functions import Transcriber_data_Functions

''' To run this scraper from bash do the following:
        cd ./path/to/YOU-DARE_scrapers-folder
        python -m post-processing.dataprep_YT.prep_data_join_YT
    Replace all paths with actual paths!
''' 

transcriber_prep = Transcriber_data_Functions()

directory = './data/Romania/cezar_lonascu_YT'
dataset_path = f'{directory}/videos.jl' # Generated by PyTube (use metadata.jl if dataset has been generated using yt-dlp)
transcriptions_dir = f'{directory}/transcribed' # Generated by prep_for_transcriber_YT
transcriber_prep.add_transcribed_text_to_video_data(dataset_path, transcriptions_dir)

print(f'\n\n\n#### Meta-data and transcibed text has been merged ####\n\n\n')



