### IMPORTS ###
import os
import json
# For scrapy
import scrapy
from scrapy.selector import Selector
from ...items import ScrapersItem
# For playwright
import asyncio
from twisted.internet.defer import inlineCallbacks, returnValue
from twisted.internet.threads import deferToThread
# For formatting and saving
from datetime import datetime
# Custom functions
from ...functions.scrapy_functions import Dynamic_Scrapy
from ...functions.general_functions import General_Functions

''' 
    This spider aims to scrape all articles from their individual article URLS (collected by another scraper).
    These links has been extracted from the bash log generated by running said other scraper.
    To run this spider pass the following to the terminal:
        cd ./YOU-DARE/scrapers
        scrapy crawl modernity_individual_links_SPIDER
    OR
        cd ./YOU-DARE/scrapers
        mkdir -p /work/YOU-DARE/scrapers/data/United_Kingdom/modernity_individual_links_SPIDER # If the folder does not yet exist
        nohup scrapy crawl modernity_individual_links_SPIDER > /work/YOU-DARE/scrapers/data/United_Kingdom/modernity_individual_links_SPIDER/modernity_individual_links_SPIDER_2025-08-28_SPIDER.log
'''

### CREATING THE SPIDER ###
class DynamicSpider(scrapy.Spider):
    name = 'modernity_individual_links_SPIDER'
    region = 'United_Kingdom'
    source = 'modernity'

    # path to the file with extracted links
    links_file = "/work/YOU-DARE/scrapers/data/United_Kingdom/modernity_SPIDER/modernity_links.jl"

    # load start_urls dynamically
    if os.path.exists(links_file):
        with open(links_file, "r", encoding="utf-8") as f:
            start_urls = [json.loads(line)["url"] for line in f]
    else:
        start_urls = []  # fallback

    ## HTML directions ##
    ''' These can be both CSS and XPath or a mix as long as it's matched within the response functions within the different parse functions.
        E.g. 'some_css' must use response.css('some_css') and 'some_xpath' must use response.xpath('some_xpath')
    '''
    # QUERIES FROM THE FRONT PAGE!!!
    ''' CSS or XPath queries for relevant information found on the front page. 
        For functionality the following queries HAVE to be found on the front page:
            links_to_follow # The links to the individual articles
            next_page # The links to the next page
        How to pass information from the parse_front function to the parse_article function will be described in greater detail later on.
    '''
    article_title_CSS = 'h1 *::text'
    author_CSS = '.cs-entry__header-info .cs-author::text'
    publication_date_CSS = '.cs-entry__header-info .cs-meta-date::text'
    article_text_bits_CSS = '.cs-entry__subtitle::text, .entry-content>p *::text, .entry-content blockquote p *::text'
    article_categories_CSS = '.cs-entry__category-label::text'
    image_links_CSS = '.entry-content figure img::attr(data-pk-src)'
    external_links_CSS = '.entry-content>p a::attr(href), .entry-content blockquote p a::attr(href)'
    embedded_media_CSS = '.entry-content iframe::attr(src)'
    # ... other queries

    ### IMPORTANT FUNCTIONS FOR SETUP THAT CANNOT BE OMITTED AND PARAMETERS SHOULD NOT BE CHANGED! ###
    def __init__(self, max_scrolls=None):
        """Initializes the spider and sets optional max_scrolls limit."""
        super().__init__()
        Dynamic_Scrapy.initialize(self, max_scrolls) # See doc string

    @classmethod
    def from_crawler(cls, crawler, *args, **kwargs): 
        """Creates the spider instance from crawler and sets it up."""
        spider = super(DynamicSpider, cls).from_crawler(crawler, *args, **kwargs)
        Dynamic_Scrapy.setup_from_crawler(spider, crawler) # See doc string
        return spider

    def open_spider(self, spider):
        """Executes setup actions when the spider is opened."""
        self.logger.info("open_spider() is running!")
        self.existing_data = Dynamic_Scrapy.load_existing_links(self.save_path) # See doc string

    ### THE ACTUAL SPIDER FUNCTIONALITY ###
    @inlineCallbacks
    def parse(self, response): # Can't be renamed
        # Renders the page and creates new selector object
        url = response.url
        page_source = yield deferToThread(asyncio.run, Dynamic_Scrapy.fetch_with_playwright(url, self.max_scrolls))

        sel = Selector(text=page_source)

        items = ScrapersItem() # Makes the items from items.py accessable within this function
        # Extract 'scrape_date'
        timestamp = datetime.now().strftime('%Y-%m-%d')
        # Extract 'article_title'
        article_title = response.css(self.article_title_CSS).get() # .get() returns only the first element. Use .getall() to return a list of all elements if more than one element is expected
        # if article_title: # Only cleans existing articles
        #     article_title_clean = General_Functions.clean_text(article_title) # Cleans the text - See doc string
        # else:
        #     article_title_clean = article_title
        # # Extract 'author' 
        author = response.css(self.author_CSS).get()
        if author: # Only cleans existing articles
            author_clean = General_Functions.clean_text(author) # Cleans the text - See doc string
        else:
            author_clean = author
        # Extract 'publication_date' 
        publication_date = response.css(self.publication_date_CSS).get()
        # Extract 'article_text'
        article_text_bits = response.css(self.article_text_bits_CSS).getall() 
        article_text_clean = General_Functions.join_and_clean(article_text_bits) # Joins and cleans all text elements - See doc string

        # Extract article_categories
        article_categories = response.css(self.article_categories_CSS).getall()
        # Extract 'image_links' 
        image_links = response.css(self.image_links_CSS).getall()
        
        # Extract 'external_links' 
        external_links = response.css(self.external_links_CSS).getall()

        # Extract 'embedded media' 
        embedded_med = response.css(self.embedded_media_CSS).getall()

        # Assign variables to items here
        items['scrape_date'] = timestamp
        items['publication_date'] = publication_date
        items['source'] = self.source
        items['article_link'] = url
        items['article_title'] = article_title
        items['author'] = author_clean
        items['article_categories'] = article_categories
        items['article_text'] = article_text_clean
        items['image_links'] = image_links
        items['embedded_media_links'] = embedded_med
        items['external_links'] = external_links
        items['other_items'] = 'None'
        items['article_HTML'] = response.text
        
        
        self.logger.info(f"Scraped article: {article_title} ({url})") # Logs successful scrape

        self.existing_data.add(url) # Adds article to list of scraped articles just in case multiple links from the front page directs to this article
        return [items]
        # yield items # returns the items to parse 